server/delire/urls.py
from django.urls import path
from django.conf import settings
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views

from . import views


urlpatterns = [
    path('', lambda request: redirect('searchPatient', permanent=False)),
	path('login', auth_views.LoginView.as_view(), {'template_name': 'login.html'}, name='login'),
	path('logout', auth_views.LogoutView.as_view(), name='logout'),
	path('createPatient', views.formPatient, name="createPatient"),
    path('updatePatient/<int:idPersonne>', views.modifierPatient, name="updatePatient"),
    path('searchPatient', views.recherchePatient, name="searchPatient"),
    path('createPersonnel', views.formPersonnel, name="createPersonnel"),
    path('updatePersonnel/<int:idPersonne>', views.modifierPersonnel, name="updatePersonnel"),
    path('searchPersonnel', views.recherchePersonnel, name="searchPersonnel"),
	path('afficheDocuments/<int:pid>', views.afficheDocuments, name="afficheDocs"),
	path('editDocument/<int:did>', views.editDocument, name="editDoc"),
	path('seeDmp/<int:pid>', views.afficheDocuments, name="dmp"),
]

server/server/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.shortcuts import redirect

from delire.views import getImports


urlpatterns = [
	path('admin/', admin.site.urls),
	path('pomme/', include('delire.urls')), # Aller voir dans delire.urls
	path('imports', getImports),
	path('', lambda request: redirect('searchPatient', permanent=False)),
]


if settings.DEBUG:
	import debug_toolbar
	urlpatterns = [
		path('__debug__/', include(debug_toolbar.urls)),

	] + urlpatterns

server/delire/models.py
from django.db import models
from django.forms import TextInput, Textarea
from django.core.mail import send_mail
from django.contrib.auth.models import User
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager

import io

#Type de Noeud
TYPES_NOEUD = (
	(0, "AP-HP"),
	(1, "Hopital"),
	(2, "Pole"),
	(3, "Service"),
	(4, "Unite-Hospitaliere"),
	(5, "Unite-Soin"),
)

JOBS = (
	(0, "Patient"),
	(1, "Secrétaire"),
	(2, "DataManager"),
	(3, "Aide-Soignant"),
	(4, "Médecin"),
)

SEXE_CHOICES = (
    ('F', 'Femme'),
    ('H', 'Homme'),
)

def getJobByNumber(x):
	if x not in list(range(5)):
		return ""
	
	return JOBS[x][1]
		
class UserManager(BaseUserManager):
	use_in_migrations = True

	def _create_user(self, email, password, **extra_fields):
		if not email:
			raise ValueError('The given email must be set')
		email = self.normalize_email(email)
		user = self.model(email=email, **extra_fields)
		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_user(self, email, password=None, **extra_fields):
		extra_fields.setdefault('is_superuser', False)
		return self._create_user(email, password, **extra_fields)

	def create_superuser(self, email, password, **extra_fields):
		extra_fields.setdefault('is_superuser', True)

		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser must have is_superuser=True.')

		return self._create_user(email, password, **extra_fields)

class Noeud(models.Model):
	nom = models.CharField(max_length=255)
	typ = models.IntegerField(choices=TYPES_NOEUD, default=2)
	pere = models.ForeignKey("Noeud", on_delete=models.CASCADE, null=True)	 #selfRef
	boss = models.ForeignKey("Personne", on_delete=models.PROTECT, null=True)

class Personne(AbstractBaseUser, PermissionsMixin):
	email = models.EmailField(max_length=255, unique=True)
	#sexe = models.BooleanField(default=True)  # True pour femme (car plus de femmes dans le monde)
	sexe = models.CharField(max_length=1, choices=SEXE_CHOICES, default='F') # True pour femme (car plus de femmes dans le monde)
	nom = models.CharField(max_length=255)
	prenom = models.CharField(max_length=255)
	dateNaissance = models.DateField()
	lieuNaissance = models.CharField(max_length=500, null=True)
	telephone = models.CharField(max_length=14, null=True)
	situationFamiliale = models.CharField(max_length=100, null=True)
	adresse = models.CharField(max_length=500)
	linkedTo = models.ForeignKey(Noeud, on_delete=models.SET_NULL, null=True)
	job = models.IntegerField(choices=JOBS, default=0)
	numSS = models.CharField(max_length=15, null=True)
	is_active = models.BooleanField(default=True)
	
	objects = UserManager()
	
	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []
	
	class Meta:
		verbose_name = 'personne'
		verbose_name_plural = 'personnes'

	def get_full_name(self):
		full_name = '%s %s' % (self.prenom, self.nom)
		return full_name.strip()

	def get_short_name(self):
		return self.prenom

	def email_user(self, subject, message, from_email=None, **kwargs):
		send_mail(subject, message, from_email, [self.email], **kwargs)
		
	def getInfos(self):
		return "{} {} : {}".format(self.prenom, self.nom, getJobByNumber(self.job))
		
	def hasMedicRights(self):
		return True if self.job in (1, 4) else False
	
	
class Specialite(models.Model):
	specialite = models.CharField(max_length=255)
	
class Document(models.Model):
	nom = models.CharField(max_length=255)
	date = models.DateField()
	brouillon = models.BooleanField(default=True)
	fichier = models.TextField()
	typeDoc = models.CharField(max_length=255)
	proprietaire = models.ForeignKey(Personne, on_delete=models.PROTECT)
	
	def getB64(self):
		return "data:image/jpeg;base64,{}".format(self.fichier)
		
	def getDate(self):
		return self.date.strftime("%d-%m-%Y")
		
	@staticmethod
	def imgToB64(img):
		from .BDD import BDD
		bdd = BDD()
		array = io.BytesIO()
		
		if img.mode == 'P':
			img = img.convert('RGB')
		
		img.save(array, format="JPEG", quality=100)
		return bdd.encrypt(array.getvalue()).decode()
		
	
class Ecrit(models.Model):
	employe = models.ForeignKey(Personne, on_delete=models.CASCADE)
	document = models.ForeignKey(Document, on_delete=models.CASCADE)
	
class EmpSpe(models.Model):
	employe = models.ForeignKey(Personne, on_delete=models.CASCADE)
	specialite = models.ForeignKey(Specialite, on_delete=models.CASCADE)
	
class NoeudSpe(models.Model):
	noeud = models.ForeignKey(Noeud, on_delete=models.CASCADE)
	specialite = models.ForeignKey(Specialite, on_delete=models.CASCADE)	
	

server/delire/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .BDD import BDD
from .forms import PatientFormEdit, PatientFormCreate, RechercheFormPatient, RechercheFormPersonnel, PersonnelFormEdit, PersonnelFormCreate, AddDocumentForm
from .models import getJobByNumber, Document

import types
from PIL import Image


def rightsRequired(*args1):
	def wrap(f):
		def decorate(request, *args, **kwargs):
			if request.user.job not in args1:
				raise PermissionDenied
			return f(request, *args, **kwargs)
		return decorate
	return wrap

@login_required
def formPatient(request): #formulaire patient
	if request.method == 'POST':
		form = PatientFormCreate(request.POST)

		if form.is_valid():
			nom = form.cleaned_data['nom']
			prenom = form.cleaned_data['prenom']
			sexe = form.cleaned_data['sexe']
			if sexe == 'F':
				sexe = 1
			else:
				sexe = 0
			date_de_naissance = form.cleaned_data['dateNaissance']
			lieu_de_naissance = form.cleaned_data['lieuNaissance']
			numero_de_SS = form.cleaned_data['numSS']
			adresse= form.cleaned_data['adresse']
			adresse_email = form.cleaned_data['email']
			téléphone = form.cleaned_data['telephone']
			situation_familiale = form.cleaned_data['situationFamiliale']

			#create
			b = BDD()
			b.createPersonne(job=0, nom=nom,
							prenom=prenom,
							sexe=sexe,
							dateNaissance=date_de_naissance,
							lieuNaissance=lieu_de_naissance,
							numSS=numero_de_SS,
							adresse=adresse,
							email=adresse_email,
							telephone=téléphone,
							situationFamiliale=situation_familiale,
							linkedTo=None)
			messages.success(request, 'Patient crée.')
		else:
			print(form.errors.as_data())  #Affiche dans la console les champs en erreur et pourquoi

		return redirect('/pomme/searchPatient')

	else:
		form = PatientFormCreate()
	
	return render(request, 'formulairepatient.html', {'form' : form})

@login_required
@rightsRequired(2)
def formPersonnel(request): #formulaire patient
	if request.method == 'POST':
		form = PersonnelFormCreate(request.POST)

		if form.is_valid():
			nom = form.cleaned_data['nom']
			prenom = form.cleaned_data['prenom']
			sexe = form.cleaned_data['sexe']
			if sexe == 'F':
				sexe = 1
			else:
				sexe = 0
			date_de_naissance = form.cleaned_data['dateNaissance']
			lieu_de_naissance = form.cleaned_data['lieuNaissance']
			job = form.cleaned_data['job'] #getJobByNumber(form.cleaned_data['job'])
			adresse= form.cleaned_data['adresse']
			adresse_email = form.cleaned_data['email']
			téléphone = form.cleaned_data['telephone']
			situation_familiale = form.cleaned_data['situationFamiliale']

			#create
			b = BDD()
			b.createPersonne(job=job, numSS=None,
							nom=nom,
							prenom=prenom,
							sexe=sexe,
							dateNaissance=date_de_naissance,
							lieuNaissance=lieu_de_naissance,
							adresse=adresse,
							email=adresse_email,
							telephone=téléphone,
							situationFamiliale=situation_familiale,
							linkedTo=None)
			messages.success(request, 'Personnel crée.')
		else:
			print(form.errors.as_data())  #Affiche dans la console les champs en erreur et pourquoi

		return redirect('/pomme/searchPersonnel')

	else:
		form = PersonnelFormCreate()
	
	return render(request, 'formulairepersonnel.html', {'form' : form})

@login_required
@rightsRequired(1, 2)
def modifierPatient(request, idPersonne): #formulaire patient
	b = BDD()
	identite = b.getPersonne(idPersonne)
	
	if request.method == 'POST':
		mod = PatientFormEdit(request.POST)

		if mod.is_valid():
			#update
			b.updatePersonne(identite, **mod.cleaned_data)
			messages.success(request, 'Modification effectuée avec succès.')

		else:
			print(mod.errors.as_data())	 #Affiche dans la console les champs en erreur et pourquoi
		
		return redirect('/pomme/searchPatient')

	else:
		dico = {'nom': identite.nom,
			   'prenom':identite.prenom,
			   'dateNaissance':identite.dateNaissance,
			   'lieuNaissance':identite.lieuNaissance,
			   'adresse':identite.adresse,
			   'email':identite.email,
			   'telephone':identite.telephone,
			   'situationFamiliale':identite.situationFamiliale,
			   }
		numSS = identite.numSS
		if(identite.sexe=="M"):
			sexe = 'Masculin'
		else:
			sexe = 'Féminin'


		mod = PatientFormEdit(initial=dico)
	print(locals())
	return render(request, 'formulairemodifpatient.html', locals())

@login_required
@rightsRequired(2)
def modifierPersonnel(request, idPersonne): #formulaire patient
	b = BDD()
	identite = b.getPersonne(idPersonne)

	if request.method == 'POST':
		mod = PersonnelFormEdit(request.POST)

		if mod.is_valid():
			#update
			b.updatePersonne(identite, **mod.cleaned_data)
			messages.success(request, 'Modification effectuée avec succès.')

		else:
			print(mod.errors.as_data())	 #Affiche dans la console les champs en erreur et pourquoi
		
		return redirect('/pomme/searchPersonnel')

	else:
		print(identite.job)
		dico = {'nom': identite.nom,
			   'prenom':identite.prenom,
			   'sexe':identite.sexe,
			   'dateNaissance':identite.dateNaissance,
			   'lieuNaissance':identite.lieuNaissance,
			   'job':identite.job, #verif et numSS ?
			   'adresse':identite.adresse,
			   'email':identite.email,
			   'telephone':identite.telephone,
			   'situationFamiliale':identite.situationFamiliale,
			   }

		if(identite.sexe=="M"):
			sexe = 'Masculin'
		else:
			sexe = 'Féminin'
		mod = PersonnelFormEdit(initial=dico)
	
	return render(request, 'formulairemodifpersonnel.html', {'mod' : mod})

@login_required
@rightsRequired(1, 2, 4)
def recherchePatient(request):
	formu = RechercheFormPatient(request.GET)

	if formu.is_valid():
		nom = formu.cleaned_data['nom']
		prenom = formu.cleaned_data['prenom']
		numSS = formu.cleaned_data['numSS']
		b = BDD()
		if prenom!='' and numSS!='': #si on trouve du premier coup
			patients = b.getAllPersonne(job=0, nom=nom, prenom=prenom, numSS=numSS)
		elif prenom!='' and numSS=='':
			patients = b.getAllPersonne(job=0, nom=nom, prenom=prenom)
		elif prenom=='' and numSS!='':
			patients = b.getAllPersonne(job=0, nom=nom, numSS=numSS)
		else: #prenom=='' and numSS==''
			patients = b.getAllPersonne(job=0, nom=nom)
		if not(patients): #si on ne trouve pas du premier coup dans la BDD
			liste = b.getAllPersonne(job=0)
			taille = len(liste)
			patients = []
			found = False
			nom = nom.lower()
			prenom = prenom.lower()
			if prenom!='' and numSS!='':
				for i in range(0,taille):
					if nom in liste[i].nom.lower() and prenom in liste[i].prenom.lower() and numSS in liste[i].numSS:
						patients.append(liste[i])
						found=True
			elif prenom!='' and numSS=='':
				for i in range(0,taille):
					if nom in liste[i].nom.lower() and prenom in liste[i].prenom.lower():
						patients.append(liste[i])
						found=True
			elif prenom=='' and numSS!='':
				for i in range(0,taille):
					if nom in liste[i].nom.lower() and numSS in liste[i].numSS:
						patients.append(liste[i])
						found=True
			else: #prenom=='' and numSS==''
				for i in range(0,taille):
					if nom in liste[i].nom.lower(): #si lettre en trop
						patients.append(liste[i])
						found=True
			if found==False:
				messages.error(request, 'Aucun patient correspondant à ces critères de recherche n’a été trouvé.')
		
		return render(request, 'recherchepatient.html', locals())
	
	
	else:
		formu = RechercheFormPatient()
		b = BDD()
		patients = b.getAllPersonne(job=0)
	
	return render(request, 'recherchepatient.html', locals())

@login_required
@rightsRequired(1, 2)
def recherchePersonnel(request):
	formu = RechercheFormPersonnel(request.GET)
	affiliation1 = "Secrétaire"
	affiliation2 = "DataManager"
	affiliation3 = "Aide-Soignant"
	affiliation4 = "Médecin"

	if formu.is_valid():
		nom = formu.cleaned_data['nom']
		prenom = formu.cleaned_data['prenom']
		b = BDD()
		if nom!='' and prenom!='':
			personnels = b.getAllPersonne(nom=nom, prenom=prenom)
		else:
			personnels = b.getAllPersonne(nom=nom)
		if not(personnels): #si on ne trouve pas du premier coup dans la BDD
			liste = b.getAllPersonne()
			taille = len(liste)
			personnels = []
			found = False
			nom = nom.lower()
			prenom = prenom.lower()
			if nom!='' and prenom!='':
				for i in range(0,taille):
					if nom in liste[i].nom.lower() and prenom in liste[i].prenom.lower():
						personnels.append(liste[i])
						found=True
			else: #prenom==''
				for i in range(0,taille):
					if nom in liste[i].nom.lower(): #si lettre en trop
						personnels.append(liste[i])
						found=True
			if found==False:
				messages.error(request, 'Aucun personnel correspondant à ces critères de recherche n’a été trouvé.')
			
			postTaille = len(personnels)
			for i in range(0,postTaille):
				if personnels[i].job == 0:
					personnels.remove(personnels[i])

		return render(request, 'recherchepersonnel.html', locals())

	else:
		formu = RechercheFormPersonnel()
		b = BDD()
		liste = b.getAllPersonne()
		taille = len(liste)
		personnels = []
		for i in range(0,taille):
			if not (liste[i].job == 0):
				personnels.append(liste[i])
	
	return render(request, 'recherchepersonnel.html', locals())

@login_required	
def rep(request): # Sinon runserver marche pas avec urls.py
	pass
		

#DMP
@login_required
@rightsRequired(1, 4)
def afficheDocuments(request, pid=""):	
	b = BDD()
	
	personne = b.getPersonne(pid)
	if personne is None:
		raise Http404
		
	documents = b.getAllDocument(proprietaire=personne)
	
	ordos = [doc for doc in documents if doc.typeDoc == "Ordonnance"]
	diagnos = [doc for doc in documents if doc.typeDoc == "Diagnostic"]
	
	pnameSurname = personne.get_full_name()
	
	if request.method == "POST":
		form = AddDocumentForm(request.POST, request.FILES)
		
		if form.is_valid():
			nom = form.cleaned_data["nom"]
			date = form.cleaned_data["date"]
			brouillon = form.cleaned_data["brouillon"]
			
			typeDoc = form.cleaned_data["typeDoc"]

server/delire/templates/delire/formulaireModifNoeud.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
	<title>Modification Noeud</title>

	<html lang="fr">
	<meta charset="UTF-8">
	<link rel="icon" type="image/png" href="{% static 'apple.png' %}" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href={% static "home.css"%}>
	<link rel="stylesheet" type="text/css" href={% static "normalize.css"%}>
	<style type="text/css">
		label{
			font-weight: 600;
		}

	</style>
</head>
<body>

	<section class="container-fluid p-0">
			
		<section class="container top-menu d-flex justify-content-between pt-2 pb-2">

			<div class="col-4">
				<img style="width: 6em;" src={% static "logo_e-pocrate.png"%}>
			</div>

			<div class="col-4 d-flex justify-content-center align-items-center">
				<img style="width: 20em;" src={% static "Logo-APHP.jpg" %}>
			</div>
			

			<div class="col-4 d-flex justify-content-end align-items-center">
				<input type="" name="" placeholder="Rechercher un DMP">
				<a href="search_dmp.html"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M23.111 20.058l-4.977-4.977c.965-1.52 1.523-3.322 1.523-5.251 0-5.42-4.409-9.83-9.829-9.83-5.42 0-9.828 4.41-9.828 9.83s4.408 9.83 9.829 9.83c1.834 0 3.552-.505 5.022-1.383l5.021 5.021c2.144 2.141 5.384-1.096 3.239-3.24zm-20.064-10.228c0-3.739 3.043-6.782 6.782-6.782s6.782 3.042 6.782 6.782-3.043 6.782-6.782 6.782-6.782-3.043-6.782-6.782zm2.01-1.764c1.984-4.599 8.664-4.066 9.922.749-2.534-2.974-6.993-3.294-9.922-.749z"/></svg></a>

			</div>
		</section>
		<section class="menu container-fluid">
			<section class="menu-inner container">
				<div class="menu_profile">
					<a class="menu_profile-txt" href="#">Jean Dupont - infirmier</a>
					<a class="btn btn-primary btn-disconnect" href="#">Déconnexion</a>
				</div>
				<div class="d-flex">
					<a class="btn btn-primary" href="#">Notifications</a>
					<a  class="btn btn-primary" href="#">Planning</a>
				</div>
			</section>
		</section>

		<section class="section-form">
			<h2>Modification des informations</h2>
			<form class="form-login" action="" method="post">
			{% csrf_token %}
				<div class="form-row">
					<div class="form-group col-md-6">
						<label for="prenom">Nom</label>
						{{ form.nom }}
					</div>
					<div class="form-group col-md-6">
						<label for="id_sexe">Type</label>
						{{ form.typ }}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label for="dateNaissance">Boss</label>
						{{ form.boss_id }}
					</div>
				    <div class="form-group col-md-6">
						<label for="id_lieuNaissance">Père</label>
						{{ form.pere_id }}
					</div>
				</div>
							
				<input type="submit" class="btn btn-primary" name="" value="Valider la modification">
			</form>
		</section>
		
	</section>
	
</body>
</html>

server/delire/templates/delire/formulairemodifpatient.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
	<title>Modification Dossier Patient</title>

	<html lang="fr">
	<meta charset="UTF-8">
	<link rel="icon" type="image/png" href="{% static 'apple.png' %}" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href={% static "home.css"%}>
	<link rel="stylesheet" type="text/css" href={% static "normalize.css"%}>
	<style type="text/css">
		label{
			font-weight: 600;
		}

	</style>
</head>
<body>

	<section class="container-fluid">

			
			<section class="container section-logo">
			<img style="width: 7em;" src={% static "logo_e-pocrate.png"%}>
			<img style="width: 15em;" src={% static "Logo-APHP.jpg" %}>
		</section>
		<section class="container top-menu d-flex justify-content-between pt-5 pb-4">
			<div class="top-menu__btns">
				<a class="top-menu__infos" href="#">{{ request.user.getInfos }}</a>
				<a class="btn btn-primary btn-disconnect" href="{% url 'logout' %}">Déconnexion</a>
			</div>

			<div>
				<a href="/pomme/searchPatient"> <input type="button" class="btn btn-primary" value="Rechercher DMP"> </a>
				<a href="/pomme/searchPersonnel"> <input type="button" class="btn btn-primary" value="Rechercher Personnel"> </a>
			</div>
		</section>
		<section class="menu container-fluid">
			<div class="container">
			</div>
		</section>

		<section class="section-form">
			<h2>Modification des informations personnelles</h2>
			<form class="form-login" action="" method="post">
			{% csrf_token %}
				<div class="form-row">
					<div class="form-group col-md-6">
						<label for="id_nom">Nom</label>
						{{ mod.nom }}
					</div>
					<div class="form-group col-md-6">
						<label for="prenom">Prénom</label>
						{{ mod.prenom }}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label for="id_sexe">Sexe</label>
						<br>
						{{ sexe }}
					</div>
						<div class="form-group col-md-6">
						<label for="dateNaissance">Date de naissance (dd/mm/aaaa)</label>
						{{ mod.dateNaissance }}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label for="id_lieuNaissance">Ville de naissance</label>
						{{ mod.lieuNaissance }}
					</div>
					<div class="form-group col-md-6">
						<label for="id_numSS">Numéro de sécurité sociale</label>
						<br>
						{{ numSS }}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label for="id_telephone">Téléphone</label>
						{{ mod.telephone }}
					</div>
					<div class="form-group col-md-6">
						<label for="id_situationFamiliale">Situation familliale</label>
						{{ mod.situationFamiliale }}
					</div>
				</div>
				

				<div class="form-group">
					<label for="id_adresse">Adresse</label>
					{{ mod.adresse }}
				</div>
			<br>
				<input type="submit" class="btn btn-primary" name="" value="Valider la modification">
			</form>
		</section>
		
	</section>
	
</body>
</html>

server/delire/templates/delire/formulairemodifpersonnel.html
<!DOCTYPE html>
<html>
<head>
    {% load staticfiles %}
	<title>Modification Dossier Personnel</title>

	<html lang="fr">
	<meta charset="UTF-8">
	<link rel="icon" type="image/png" href="{% static 'apple.png' %}" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css" integrity="sha384-PDle/QlgIONtM1aqA2Qemk5gPOE7wFq8+Em+G/hmo5Iq0CCmYZLv3fVRDJ4MMwEA" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href={% static "home.css"%}>
	<link rel="stylesheet" type="text/css" href={% static "normalize.css"%}>
	<style type="text/css">
		label{
			font-weight: 600;
		}

	</style>
</head>
<body>

			<section class="container section-logo">
			<img style="width: 7em;" src={% static "logo_e-pocrate.png"%}>
			<img style="width: 15em;" src={% static "Logo-APHP.jpg" %}>
		</section>
		<section class="container top-menu d-flex justify-content-between pt-5 pb-4">
			<div class="top-menu__btns">
				<a class="top-menu__infos" href="#">{{ request.user.getInfos }}</a>
				<a class="btn btn-primary btn-disconnect" href="{% url 'logout' %}">Déconnexion</a>
			</div>

			<div>
				<a href="/pomme/searchPatient"> <input type="button" class="btn btn-primary" value="Rechercher DMP"> </a>
				<a href="/pomme/searchPersonnel"> <input type="button" class="btn btn-primary" value="Rechercher Personnel"> </a>
			</div>
		</section>
		<section class="menu container-fluid">
			<div class="container">
			</div>
		</section>

		<section class="section-form">
			<h2>Modification des informations personnelles</h2>
			<form class="form-login" action="" method="post">
			{% csrf_token %}
				<div class="form-row">
					<div class="form-group col-md-6">
						<label for="id_nom">Nom</label>
						{{ mod.nom }}
					</div>
					<div class="form-group col-md-6">
						<label for="prenom">Prénom</label>
						{{ mod.prenom }}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label for="id_sexe">Sexe</label>
						<br>
						{{ sexe }}
					</div>
						<div class="form-group col-md-6">
						<label for="dateNaissance">Date de naissance (dd/mm/aaaa)</label>
						{{ mod.dateNaissance }}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label for="id_lieuNaissance">Ville de naissance</label>
						{{ mod.lieuNaissance }}
					</div>
					<div class="form-group col-md-6">
						<label for="id_job">Affiliation</label>
						{{ mod.job }}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label for="id_telephone">Téléphone</label>
						{{ mod.telephone }}
					</div>
					<div class="form-group col-md-6">
						<label for="id_situationFamiliale">Situation familliale</label>
						{{ mod.situationFamiliale }}
					</div>
				</div>
				

				<div class="form-group">
					<label for="id_adresse">Adresse</label>
					{{ mod.adresse }}
				</div>
				<input type="submit" class="btn btn-primary" name="" value="Valider la modification">
			</form>
		</section>
		
	</section>
	
</body>
</html>